[package]
name = "binc"
version = "0.1.0"
authors = ["artem"]
edition = "2018"

[dependencies]
clap = "2.33.3"
#bigdecimal = "0.2.0"
log = "0.4"
rustyline = "8.0.0"
stderrlog = "0.4"
colored = "2"
smallvec = "1.6.1"
rand = "0.8.3"
